[profile.default]
solc_version = "0.8.16"
optimizer = true
optimizer_runs = 200

test = "contracts/tests"

libs = [
    "lib",
    "node_modules",
]

out = "build/out"

cache_path = "build/cache"

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidity-parser/=node_modules/@solidity-parser/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "wormhole-solidity/=contracts/tests/helpers/modules",
]

[profile.testnet]
broadcast = "build/broadcast"

[profile.mainnet]
broadcast = "mainnet-deploy/broadcast"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
