[features]
seeds = false
skip-lint = false

[programs.localnet]
### WARNING: Be sure to change these pubkeys to reflect your deployed keypairs
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
xchain_token = "2n1p8eEw2CDiwastC3rVPYPEJzZdUpBBhJJWMTwLYty3"

[programs.devnet]
### WARNING: Be sure to change these pubkeys to reflect your deployed keypairs
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
xchain_token = "2n1p8eEw2CDiwastC3rVPYPEJzZdUpBBhJJWMTwLYty3"

[programs.mainnet]
### WARNING: Be sure to change these pubkeys to reflect your deployed keypairs
hello_world = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
xchain_token = "EcNezEFFnaWCoWqPMgBPV8b574Js3QBUiLqizvM11ZF3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "key/payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 ts/tests/sol-eth/mainnet/test_transfer.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dependencies/spl_token_metadata.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "./dependencies/wormhole.so"

### NOTE: Check against testing.env
[[test.genesis]]
address = "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb"
program = "./dependencies/token_bridge.so"
