name: Injective CI

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_VERSION: v1.14.14
  ANCHOR_VERSION: 0.26.0

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install Cargo
        uses: actions-rs/cargo@v1
      - name: Install Wasm
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "/home/runner/.cargo/bin" >> $GITHUB_PATH
          sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
          rustup target add wasm32-unknown-unknown # Add the wasm toolchain
      - name: Install typescript
        run: npm i -g ts-mocha typescript
      - name: Build
        run: |
          cd injective/contracts
          yarn clean
          yarn build
      - name: Lint
        run: |
          cd injective/contracts
          yarn lint
