name: Solana CI

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_VERSION: v1.14.14
  ANCHOR_VERSION: 0.26.0

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './solana/package-lock.json'
      - name: Install Cargo
        uses: actions-rs/cargo@v1
      - name: Install Solana
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "/home/runner/.cargo/bin" >> $GITHUB_PATH
          curl -sSfL https://release.solana.com/$SOLANA_VERSION/install | sh
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Install Anchor
        run: npm i -g @project-serum/anchor-cli@$ANCHOR_VERSION ts-mocha typescript
      - name: Build
        run: |
          cd solana
          make dependencies
      - name: Run unit-test
        run: |
          cd solana
          make unit-test
      - name: Run integration-test
        run: |
          cd solana
          make integration-test
